/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonComponent: typeof import('./src/components/button/ui/ButtonComponent.vue')['default']
    CardComponent: typeof import('./src/components/card/ui/CardComponent.vue')['default']
    FormComponent: typeof import('./src/components/form/ui/FormComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
